FROM node:20.10.0-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y fish git && \
    rm -rf /var/lib/apt/lists/* && \
    sed -i 's|/bin/bash|/usr/bin/fish|g' /etc/passwd && \
    npm install -g npm@6

EXPOSE 5000

COPY start.sh .

ENTRYPOINT ["/bin/bash", "/app/start.sh"]